"common conf {{             通用配置
set ai                      "自动缩进
set bs=2                    "在insert模式下用退格键删除
set showmatch               "代码匹配
set laststatus=2            "总是显示状态行

"设置自动缩进
"设置智能缩进
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab
set smarttab

set cursorline              "为光标所在行加下划线
set number                  "显示行号
set autoread                "文件在Vim之外修改过，自动重新读入

set ignorecase              "检索时忽略大小写
set fileencodings=uft-8,gbk "使用utf-8或gbk打开文件
set hls                     "检索时高亮显示匹配项
set foldmethod=syntax       "代码折叠
set bg=dark                 "设置背景色
set ruler                   "总是在窗口右下角显示光标位置
"}}

" conf for tabs, 为标签页进行的配置，通过ctrl h/l切换标签等
let mapleader = ','
nnoremap <C-l> gt
nnoremap <C-h> gT
nnoremap <leader>t : tabe<CR>

" Pathogen
call pathogen#infect()
syntax on
call pathogen#helptags() " generate helptags for everything in 'runtimepath'
filetype plugin indent on

" Management of plugins installed {{
" Give a shortcut key to Nerdtree
map <F2> :NERDTreeToggle<CR>
" Give a shortcut key to Taglist
map <F3> :TlistToggle<CR>
" Open Taglist plugin to the right side of the window
let Tlist_Use_Right_Window=1
" Plugin vim-colors-solarized
syntax enable
if has('gui_running')
    set background=light    " For mvim or gvim
else
    set background=dark     " For vim
endif
colorscheme solarized
" }} 
